### ISSUE TITLE
The access key ID you provided does not exist in our records.

### ISSUE THREAD

**Issue by bearmoo-repo** [minio/minfs-docker-plugin#1]
I have tried testing out this driver for docker and I see that I am getting this error:

INFO[0000] listening on /run/docker/plugins/minfs.sock  
ERRO[0012] Volume not found.                             operation=unmount volume=test
ERRO[0012] volume service not found                     
FATA[0012] The access key ID you provided does not exist in our records.  bucket=test endpoint=http://xx.xx.xx.xxx:9000

ANy idea why?

**Comment by hackintoshrao** [comment]
Can you pass the access key using the `-o access-key=Q3AM3UQ867SPQQA43P2F \` option and try agin.

**Comment by harshavardhana** [comment]
> I have tried testing out this driver for docker and I see that I am getting this error:
> 
> INFO[0000] listening on /run/docker/plugins/minfs.sock
> ERRO[0012] Volume not found. operation=unmount volume=test
> ERRO[0012] volume service not found
> FATA[0012] The access key ID you provided does not exist in our records. bucket=test endpoint=http://xx.xx.xx.xxx:9000
> 
> ANy idea why?

Just FYI this project is not ready to be used yet we are still working out some internal issues. So please stay tuned @bearmoo-repo

**Comment by bearmoo-repo** [comment]
Hi,

So I did pass the option access-key, and that's what brought that error message. Should I will stay tuned.

**Comment by hackintoshrao** [comment]
> The access key ID you provided does not exist in our records. bucket=test endpoint=http://xx.xx.xx.xxx:9000

The above error suggests the `access-key` provided doesn't exist in minio server at given endpoint. That should work fine. But stay tuned to enable the writes from containers into the mounted volume.

**Comment by hackintoshrao** [comment]
@bearmoo-repo : The plugin is ready. Please follow the instructions in updated `README.md`. Let us know once you validate the plugin.

**Comment by bearmoo-repo** [comment]
Sure, will do!

**Comment by bearmoo-repo** [comment]
I notice a few things.

When I run:
docker volume create -d minio/minfs --name test -o endpoint=http://xx.xx.xx.xx:9002 -o access-key=yyy -o secret-key=xxx -o bucket=test
 then
docker run -it -v test:/data busybox /bin/sh

I am not able to see any files in /data, and I see that the minfs proccess gets into a defun state:
root      7041  6953  0 22:13 ?        00:00:00 [minfs] <defunct>

If kill it and rerun docker run -it -v test:/data busybox /bin/sh I can see the files, but I see minfs still gets defunct:

root      7292  6953  0 22:15 ?        00:00:00 [minfs] <defunct>
root      7416  6953  0 22:19 ?        00:00:00 [minfs] <defunct>


Any idea?

**Comment by hackintoshrao** [comment]
@bearmoo-repo : Can you give me details of your environment? Atleast the OS you are running on and your `docker version` ?

**Comment by harshavardhana** [comment]
@bearmoo-repo just used docker 1.13 on a fresh setup 

```
$ docker volume create -d minio/minfs   --name my-test-store   -o endpoint=https://play.minio.io:9000   -o access-key=Q3AM3UQ867SPQQA43P2F   -o secret-key=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG   -o bucket=testbucket

$ docker run --rm -it -v my-test-store:/data busybox /bin/sh

/ # df -h /data
Filesystem                Size      Used Available Use% Mounted on
MinFS                    64.0T         0     64.0T   0% /data
``` 

Seems to be running fine would you mind using "https://play.minio.io:9000" and testing it?

**Comment by harshavardhana** [comment]
another additional question is does container has access to the Minio server? are you running minio also inside a container on the same networking?

**Comment by harshavardhana** [comment]
Also tried with AWS S3 which seems to be working as well. 

```
$ docker volume create -d minio/minfs --name my-test-store -o endpoint=https://s3.amazonaws.com   -o access-key=xxxxxxxxxx   -o secret-key=xxxxxxxxxxxxxxx   -o bucket=andoria
my-test-store
$ docker run --rm -it -v my-test-store:/data busybox /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
none                     54.9G     26.2G     25.9G  50% /
tmpfs                     7.6G         0      7.6G   0% /dev
tmpfs                     7.6G         0      7.6G   0% /sys/fs/cgroup
MinFS                    64.0T         0     64.0T   0% /data
/dev/sda2                54.9G     26.2G     25.9G  50% /etc/resolv.conf
/dev/sda2                54.9G     26.2G     25.9G  50% /etc/hostname
/dev/sda2                54.9G     26.2G     25.9G  50% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     7.6G         0      7.6G   0% /proc/kcore
tmpfs                     7.6G         0      7.6G   0% /proc/timer_list
tmpfs                     7.6G         0      7.6G   0% /proc/timer_stats
tmpfs                     7.6G         0      7.6G   0% /proc/sched_debug
tmpfs                     7.6G         0      7.6G   0% /sys/firmware
/ # ls /data/
1.txt            2                2.txt            3.txt            CONTRIBUTING.md  issue            packbuck         tmp
```

**Comment by harshavardhana** [comment]
Another set of tests with docker compose

```
$ docker-compose up
Creating minio_minio3_1
Creating minio_minio2_1
Creating minio_minio4_1
Creating minio_minio1_1
Attaching to minio_minio2_1, minio_minio4_1, minio_minio1_1, minio_minio3_1
minio2_1  | Created minio configuration file successfully at /root/.minio
minio1_1  | Created minio configuration file successfully at /root/.minio
minio4_1  | Created minio configuration file successfully at /root/.minio
minio3_1  | Created minio configuration file successfully at /root/.minio
``` 

```
$ docker volume create -d minio/minfs --name my-test-store -o endpoint=http://172.18.0.2:9000 -o access-key=minio -o secret-key=minio123 -o bucket=testbucket
my-test-store
$ docker run --rm -it -v my-test-store:/data busybox /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
none                     54.9G     26.3G     25.8G  50% /
tmpfs                     7.6G         0      7.6G   0% /dev
tmpfs                     7.6G         0      7.6G   0% /sys/fs/cgroup
MinFS                    64.0T         0     64.0T   0% /data
/dev/sda2                54.9G     26.3G     25.8G  50% /etc/resolv.conf
/dev/sda2                54.9G     26.3G     25.8G  50% /etc/hostname
/dev/sda2                54.9G     26.3G     25.8G  50% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     7.6G         0      7.6G   0% /proc/kcore
tmpfs                     7.6G         0      7.6G   0% /proc/timer_list
tmpfs                     7.6G         0      7.6G   0% /proc/timer_stats
tmpfs                     7.6G         0      7.6G   0% /proc/sched_debug
tmpfs                     7.6G         0      7.6G   0% /sys/firmware
/ # df -h /data
Filesystem                Size      Used Available Use% Mounted on
MinFS                    64.0T         0     64.0T   0% /data
``` 

Seems to be fine as well.

**Comment by bearmoo-repo** [comment]
The environment Compose like this:

All hosts have:
OS: Centos 7.2
Docker Version: 1.13.0

Network is layout is flat and every host has a network overlay that is manage though rancher with a general network for all hosts to communicate on. On one host, there are four minio instance in a Distributed setup behind a loadbalancer. On a another host, I am trying to connect to those four instances using the docker plugin. For now there is not ssl enable on them and I am able communicate with the minio distributed using mc.

**Comment by harshavardhana** [comment]
@bearmoo-repo would it possible access your setup ?

**Comment by bearmoo-repo** [comment]
Please email me at zorbustheknight@gmail.com.

**Comment by harshavardhana** [comment]
Closing this bug we migrated this code to github.com/minio/minfs
